# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f371dfa2d2e31a7249ee6b41d4873a04a2a63a89560461243a46eeb25a5e55041ce031bc08ff782d61ce8893365d16cb0e764a56824d44edfafe01b7bf042e39

test:
  secret_key_base: d1d8bf4bff764f01295b5b33c31ab9e4db1f8f2401a186a8b4fda7b6b87ddcc591ab262dd2055fa7c2e3da800d176c0db6f4547fc5c8e924a2533db39f3cb92d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
